[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "mixed-assignment"
start_line = 104
end_line = 104

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "mixed-assignment"
start_line = 111
end_line = 111

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "mixed-operand"
start_line = 93
end_line = 93

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "mixed-operand"
start_line = 108
end_line = 108

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "mixed-operand"
start_line = 115
end_line = 115

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "mixed-operand"
start_line = 190
end_line = 190

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "possibly-null-argument"
start_line = 130
end_line = 130

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "possibly-null-argument"
start_line = 146
end_line = 146

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "possibly-null-argument"
start_line = 166
end_line = 166

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "docblock-type-mismatch"
start_line = 123
end_line = 123

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "less-specific-nested-argument-type"
start_line = 129
end_line = 129

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 106
end_line = 106

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 112
end_line = 112

[[entries."src/Core/Config.php".issues]]
code = "mixed-argument"
start_line = 71
end_line = 71

[[entries."src/Core/Config.php".issues]]
code = "mixed-array-access"
start_line = 59
end_line = 59

[[entries."src/Core/Config.php".issues]]
code = "mixed-array-access"
start_line = 71
end_line = 71

[[entries."src/Core/Config.php".issues]]
code = "mixed-assignment"
start_line = 59
end_line = 59

[[entries."src/Core/Config.php".issues]]
code = "mixed-assignment"
start_line = 67
end_line = 67

[[entries."src/Core/Config.php".issues]]
code = "reference-to-undefined-variable"
start_line = 70
end_line = 70

[[entries."src/Core/Config.php".issues]]
code = "undefined-variable"
start_line = 71
end_line = 71

[[entries."src/Core/Container.php".issues]]
code = "invalid-callable"
start_line = 56
end_line = 56

[[entries."src/Core/Container.php".issues]]
code = "invalid-property-assignment-value"
start_line = 80
end_line = 80

[[entries."src/Core/Container.php".issues]]
code = "invalid-return-statement"
start_line = 103
end_line = 103

[[entries."src/Core/Container.php".issues]]
code = "less-specific-nested-return-statement"
start_line = 130
end_line = 130

[[entries."src/Core/Container.php".issues]]
code = "mixed-argument"
start_line = 61
end_line = 61

[[entries."src/Core/Container.php".issues]]
code = "mixed-argument"
start_line = 127
end_line = 127

[[entries."src/Core/Container.php".issues]]
code = "mixed-assignment"
start_line = 55
end_line = 55

[[entries."src/Core/Container.php".issues]]
code = "mixed-property-type-coercion"
start_line = 63
end_line = 63

[[entries."src/Core/Container.php".issues]]
code = "mixed-return-statement"
start_line = 65
end_line = 65

[[entries."src/Core/Container.php".issues]]
code = "nullable-return-statement"
start_line = 103
end_line = 103

[[entries."src/Core/Container.php".issues]]
code = "too-many-arguments"
start_line = 88
end_line = 88

[[entries."src/Core/Container.php".issues]]
code = "unevaluated-code"
start_line = 67
end_line = 67

[[entries."src/Core/Container.php".issues]]
code = "unknown-class-instantiation"
start_line = 98
end_line = 98

[[entries."src/Core/Security.php".issues]]
code = "mixed-property-type-coercion"
start_line = 13
end_line = 16

[[entries."src/Core/System.php".issues]]
code = "mixed-assignment"
start_line = 40
end_line = 40

[[entries."src/Core/System.php".issues]]
code = "mixed-operand"
start_line = 43
end_line = 43

[[entries."src/Core/System.php".issues]]
code = "mixed-operand"
start_line = 43
end_line = 43

[[entries."src/Core/YamlParser.php".issues]]
code = "mismatched-array-index"
start_line = 56
end_line = 56

[[entries."src/Core/YamlParser.php".issues]]
code = "mismatched-array-index"
start_line = 78
end_line = 78

[[entries."src/Core/YamlParser.php".issues]]
code = "mixed-argument"
start_line = 60
end_line = 60

[[entries."src/Core/YamlParser.php".issues]]
code = "mixed-argument"
start_line = 66
end_line = 66

[[entries."src/Core/YamlParser.php".issues]]
code = "mixed-array-access"
start_line = 68
end_line = 68

[[entries."src/Core/YamlParser.php".issues]]
code = "mixed-array-assignment"
start_line = 83
end_line = 83

[[entries."src/Core/YamlParser.php".issues]]
code = "mixed-array-assignment"
start_line = 91
end_line = 91

[[entries."src/Core/YamlParser.php".issues]]
code = "mixed-array-assignment"
start_line = 93
end_line = 93

[[entries."src/Core/YamlParser.php".issues]]
code = "mixed-assignment"
start_line = 56
end_line = 56

[[entries."src/Core/YamlParser.php".issues]]
code = "mixed-assignment"
start_line = 78
end_line = 78

[[entries."src/Core/YamlParser.php".issues]]
code = "mixed-assignment"
start_line = 82
end_line = 82

[[entries."src/Router/Router.php".issues]]
code = "mixed-argument"
start_line = 118
end_line = 118

[[entries."src/Router/Router.php".issues]]
code = "mixed-argument"
start_line = 121
end_line = 121

[[entries."src/Router/Router.php".issues]]
code = "mixed-argument"
start_line = 209
end_line = 209

[[entries."src/Router/Router.php".issues]]
code = "mixed-assignment"
start_line = 117
end_line = 117

[[entries."src/Router/Router.php".issues]]
code = "mixed-assignment"
start_line = 208
end_line = 208

[[entries."src/Router/Router.php".issues]]
code = "non-existent-method"
start_line = 130
end_line = 130

[[entries."src/Router/Router.php".issues]]
code = "non-existent-method"
start_line = 130
end_line = 130

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "mismatched-array-index"
start_line = 29
end_line = 29

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "mismatched-array-index"
start_line = 30
end_line = 30

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "mismatched-array-index"
start_line = 33
end_line = 33

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "mismatched-array-index"
start_line = 33
end_line = 33

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "mismatched-array-index"
start_line = 42
end_line = 42

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "mismatched-array-index"
start_line = 43
end_line = 43

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "mixed-operand"
start_line = 99
end_line = 99

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "non-existent-method"
start_line = 45
end_line = 45

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "non-existent-method"
start_line = 61
end_line = 61

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 31
end_line = 31

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 31
end_line = 31

[[entries."tests/src/Abstract/Helper/ConcreteTestSecurity.php".issues]]
code = "mixed-property-type-coercion"
start_line = 17
end_line = 20

[[entries."tests/src/Abstract/Helper/WebKernel.php".issues]]
code = "less-specific-return-statement"
start_line = 37
end_line = 37

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "possibly-null-argument"
start_line = 120
end_line = 120

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "string-member-selector"
start_line = 125
end_line = 125

[[entries."tests/src/Core/YamlParserTest.php".issues]]
code = "invalid-property-assignment-value"
start_line = 185
end_line = 185

[[entries."tests/src/Core/YamlParserTest.php".issues]]
code = "invalid-return-statement"
start_line = 187
end_line = 187

[[entries."tests/src/Core/YamlParserTest.php".issues]]
code = "nullable-return-statement"
start_line = 187
end_line = 187

[[entries."tests/src/Core/YamlParserTest.php".issues]]
code = "possibly-null-argument"
start_line = 186
end_line = 186

[[entries."tests/src/Factory/ContainerFactoryTest.php".issues]]
code = "invalid-method-access"
start_line = 36
end_line = 36

[[entries."tests/src/Factory/ContainerFactoryTest.php".issues]]
code = "invalid-method-access"
start_line = 37
end_line = 37

[[entries."tests/src/Factory/ContainerFactoryTest.php".issues]]
code = "mixed-argument"
start_line = 37
end_line = 37

[[entries."tests/src/Factory/ContainerFactoryTest.php".issues]]
code = "mixed-argument"
start_line = 37
end_line = 37

[[entries."tests/src/Factory/ContainerFactoryTest.php".issues]]
code = "possibly-null-operand"
start_line = 90
end_line = 90

[[entries."tests/src/TestCase.php".issues]]
code = "mixed-argument"
start_line = 95
end_line = 95

[[entries."tests/src/TestCase.php".issues]]
code = "mixed-operand"
start_line = 18
end_line = 18

[[entries."tests/src/TestCase.php".issues]]
code = "mixed-operand"
start_line = 40
end_line = 40

[[entries."tests/src/TestCase.php".issues]]
code = "non-existent-property"
start_line = 117
end_line = 117

[[entries."tests/src/TestCase.php".issues]]
code = "possibly-false-argument"
start_line = 52
end_line = 52

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "possibly-invalid-argument"
start_line = 118
end_line = 118
