[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "cyclomatic-complexity"
start_line = 28
end_line = 247

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "too-many-methods"
start_line = 14
end_line = 255

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "too-many-properties"
start_line = 14
end_line = 255

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "cyclomatic-complexity"
start_line = 18
end_line = 192

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "kan-defect"
start_line = 18
end_line = 192

[[entries."src/Core/Container.php".issues]]
code = "halstead"
start_line = 40
end_line = 69

[[entries."src/Core/YamlParser.php".issues]]
code = "cyclomatic-complexity"
start_line = 13
end_line = 131

[[entries."src/Interface/RequestInterface.php".issues]]
code = "too-many-methods"
start_line = 8
end_line = 131

[[entries."src/Router/Router.php".issues]]
code = "cyclomatic-complexity"
start_line = 16
end_line = 281

[[entries."src/Router/Router.php".issues]]
code = "excessive-nesting"
start_line = 131
end_line = 135

[[entries."src/Router/Router.php".issues]]
code = "halstead"
start_line = 57
end_line = 73

[[entries."src/Router/Router.php".issues]]
code = "kan-defect"
start_line = 16
end_line = 281

[[entries."tests/src/Abstract/AbstractResponseTest.php".issues]]
code = "cyclomatic-complexity"
start_line = 15
end_line = 122

[[entries."tests/src/AbstractTestCase.php".issues]]
code = "too-many-methods"
start_line = 18
end_line = 163

[[entries."tests/src/Core/ContainerTest.php".issues]]
code = "too-many-methods"
start_line = 19
end_line = 140

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "no-global"
start_line = 116
end_line = 116

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "cyclomatic-complexity"
start_line = 15
end_line = 258

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "cyclomatic-complexity"
start_line = 21
end_line = 257

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "return-type"
start_line = 165
end_line = 167
