[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "invalid-iterator"
start_line = 81
end_line = 81

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "invalid-property-read"
start_line = 80
end_line = 80

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "mixed-property-access"
start_line = 81
end_line = 81

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "redundant-comparison"
start_line = 80
end_line = 80

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "redundant-logical-operation"
start_line = 80
end_line = 80

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "ambiguous-instantiation-target"
start_line = 97
end_line = 97

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "docblock-type-mismatch"
start_line = 110
end_line = 110

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-class-string-expression"
start_line = 97
end_line = 97

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-class-string-expression"
start_line = 97
end_line = 97

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 79
end_line = 79

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 79
end_line = 79

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 130
end_line = 130

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 130
end_line = 130

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-argument"
start_line = 100
end_line = 100

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-argument"
start_line = 104
end_line = 104

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-argument"
start_line = 105
end_line = 105

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 99
end_line = 99

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 99
end_line = 99

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-property-type-coercion"
start_line = 49
end_line = 49

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "named-argument-not-allowed"
start_line = 100
end_line = 100

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-value"
start_line = 79
end_line = 79

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "non-existent-property"
start_line = 49
end_line = 49

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "non-existent-property"
start_line = 49
end_line = 49

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possibly-invalid-argument"
start_line = 115
end_line = 115

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possibly-invalid-iterator"
start_line = 99
end_line = 99

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "property-type-coercion"
start_line = 50
end_line = 50

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "redundant-comparison"
start_line = 130
end_line = 130

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "redundant-condition"
start_line = 130
end_line = 130

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "unknown-class-instantiation"
start_line = 97
end_line = 97

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "unknown-class-instantiation"
start_line = 101
end_line = 101

[[entries."src/Abstract/AbstractSecurity.php".issues]]
code = "named-argument-not-allowed"
start_line = 28
end_line = 28

[[entries."src/Attribute/Configuration.php".issues]]
code = "mixed-operand"
start_line = 32
end_line = 32

[[entries."src/Attribute/Configuration.php".issues]]
code = "mixed-operand"
start_line = 33
end_line = 33

[[entries."src/Core/Security.php".issues]]
code = "invalid-property-read"
start_line = 14
end_line = 14

[[entries."src/Core/System.php".issues]]
code = "impossible-assignment"
start_line = 35
end_line = 35

[[entries."src/Core/System.php".issues]]
code = "invalid-property-read"
start_line = 35
end_line = 35

[[entries."src/Core/System.php".issues]]
code = "invalid-property-read"
start_line = 44
end_line = 44

[[entries."src/Core/System.php".issues]]
code = "no-value"
start_line = 44
end_line = 44

[[entries."src/Exception/WaffleException.php".issues]]
code = "invalid-return-statement"
start_line = 23
end_line = 27

[[entries."src/Router/Router.php".issues]]
code = "invalid-property-assignment-value"
start_line = 156
end_line = 156

[[entries."src/Router/Router.php".issues]]
code = "invalid-property-read"
start_line = 242
end_line = 242

[[entries."src/Router/Router.php".issues]]
code = "named-argument-not-allowed"
start_line = 99
end_line = 99

[[entries."src/Router/Router.php".issues]]
code = "named-argument-not-allowed"
start_line = 100
end_line = 100

[[entries."src/Router/Router.php".issues]]
code = "named-argument-not-allowed"
start_line = 239
end_line = 239

[[entries."src/Router/Router.php".issues]]
code = "non-existent-method"
start_line = 140
end_line = 140

[[entries."src/Router/Router.php".issues]]
code = "non-existent-method"
start_line = 140
end_line = 140

[[entries."src/Router/Router.php".issues]]
code = "possible-method-access-on-null"
start_line = 140
end_line = 140

[[entries."src/Router/Router.php".issues]]
code = "possibly-invalid-argument"
start_line = 131
end_line = 131

[[entries."src/Router/Router.php".issues]]
code = "property-type-coercion"
start_line = 69
end_line = 69

[[entries."src/Router/Router.php".issues]]
code = "reference-to-undefined-variable"
start_line = 228
end_line = 228

[[entries."src/Router/Router.php".issues]]
code = "unknown-class-instantiation"
start_line = 116
end_line = 116

[[entries."src/Router/Router.php".issues]]
code = "unknown-class-instantiation"
start_line = 240
end_line = 240

[[entries."src/Trait/DotenvTrait.php".issues]]
code = "mixed-operand"
start_line = 15
end_line = 15

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "invalid-generator-return-type"
start_line = 82
end_line = 82

[[entries."src/Trait/RenderingTrait.php".issues]]
code = "possibly-invalid-argument"
start_line = 24
end_line = 24

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 103
end_line = 103

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 123
end_line = 123

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 145
end_line = 145

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 151
end_line = 151

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 152
end_line = 152

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 184
end_line = 184

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 190
end_line = 190

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 191
end_line = 191

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 216
end_line = 216

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 238
end_line = 238

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 260
end_line = 260

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 296
end_line = 296

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 297
end_line = 297

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 321
end_line = 321

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 322
end_line = 322

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 161
end_line = 161

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 161
end_line = 161

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 271
end_line = 271

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 271
end_line = 271

[[entries."tests/src/Abstract/AbstractResponseTest.php".issues]]
code = "possibly-null-property-access"
start_line = 52
end_line = 52

[[entries."tests/src/Abstract/Helper/ConcreteTestKernel.php".issues]]
code = "missing-override-attribute"
start_line = 27
end_line = 27

[[entries."tests/src/Abstract/Helper/ConcreteTestKernel.php".issues]]
code = "mixed-operand"
start_line = 33
end_line = 33

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "mixed-return-statement"
start_line = 23
end_line = 23

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "mixed-return-statement"
start_line = 28
end_line = 28

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "non-existent-property"
start_line = 23
end_line = 23

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "non-existent-property"
start_line = 28
end_line = 28

[[entries."tests/src/Abstract/Helper/ConcreteTestSecurity.php".issues]]
code = "unused-parameter"
start_line = 15
end_line = 15

[[entries."tests/src/Abstract/Helper/ControllableTestRequest.php".issues]]
code = "missing-override-attribute"
start_line = 31
end_line = 31

[[entries."tests/src/Abstract/Helper/LoadEnvDisabledKernel.php".issues]]
code = "missing-override-attribute"
start_line = 16
end_line = 16

[[entries."tests/src/Abstract/Helper/WebKernel.php".issues]]
code = "missing-override-attribute"
start_line = 17
end_line = 17

[[entries."tests/src/Abstract/Helper/WebKernel.php".issues]]
code = "missing-override-attribute"
start_line = 29
end_line = 29

[[entries."tests/src/Abstract/Helper/WebKernel.php".issues]]
code = "missing-override-attribute"
start_line = 37
end_line = 37

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 22
end_line = 22

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 23
end_line = 23

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 39
end_line = 39

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 40
end_line = 40

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "string-member-selector"
start_line = 124
end_line = 124

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 131
end_line = 131

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 136
end_line = 136

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 195
end_line = 195

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 204
end_line = 204

[[entries."tests/src/Core/SecurityTest.php".issues]]
code = "mixed-assignment"
start_line = 28
end_line = 28

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "invalid-property-read"
start_line = 43
end_line = 43

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "invalid-property-read"
start_line = 85
end_line = 85

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "no-value"
start_line = 43
end_line = 43

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "no-value"
start_line = 85
end_line = 85

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 78
end_line = 78

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 104
end_line = 104

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 126
end_line = 126

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 158
end_line = 158

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 205
end_line = 205

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "mixed-argument"
start_line = 184
end_line = 184

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "mixed-assignment"
start_line = 182
end_line = 182

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 78
end_line = 78

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 79
end_line = 79

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 112
end_line = 112

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 134
end_line = 134

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 205
end_line = 205

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 24
end_line = 24

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 25
end_line = 25

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 61
end_line = 61

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 61
end_line = 61

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 63
end_line = 63

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 63
end_line = 63

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 83
end_line = 83

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 83
end_line = 83

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 85
end_line = 85

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 85
end_line = 85

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-assignment"
start_line = 30
end_line = 30

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-method-access"
start_line = 63
end_line = 63

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-operand"
start_line = 34
end_line = 34

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-operand"
start_line = 38
end_line = 38

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "ambiguous-object-method-access"
start_line = 38
end_line = 38

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "ambiguous-object-method-access"
start_line = 59
end_line = 59

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "ambiguous-object-method-access"
start_line = 76
end_line = 76

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "possibly-invalid-argument"
start_line = 121
end_line = 121

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "unused-parameter"
start_line = 179
end_line = 179

[[entries."tests/src/Trait/SystemTraitTest.php".issues]]
code = "possibly-false-argument"
start_line = 23
end_line = 23
