[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 94
end_line = 94

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-global"
start_line = 16
end_line = 16

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-request-variable"
start_line = 65
end_line = 65

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "too-many-properties"
start_line = 10
end_line = 122

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 98
end_line = 98

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-global"
start_line = 20
end_line = 20

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-request-variable"
start_line = 69
end_line = 69

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "too-many-properties"
start_line = 12
end_line = 139

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "cyclomatic-complexity"
start_line = 17
end_line = 177

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "kan-defect"
start_line = 17
end_line = 177

[[entries."src/Attribute/Configuration.php".issues]]
code = "no-shorthand-ternary"
start_line = 31
end_line = 31

[[entries."src/Attribute/Configuration.php".issues]]
code = "no-shorthand-ternary"
start_line = 32
end_line = 32

[[entries."src/Core/Cli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 10
end_line = 10

[[entries."src/Core/Request.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 10
end_line = 10

[[entries."src/Interface/CliInterface.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 36
end_line = 36

[[entries."src/Interface/RequestInterface.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 36
end_line = 36

[[entries."src/Router/Router.php".issues]]
code = "cyclomatic-complexity"
start_line = 15
end_line = 309

[[entries."src/Router/Router.php".issues]]
code = "excessive-nesting"
start_line = 131
end_line = 138

[[entries."src/Router/Router.php".issues]]
code = "halstead"
start_line = 56
end_line = 72

[[entries."src/Router/Router.php".issues]]
code = "kan-defect"
start_line = 15
end_line = 309

[[entries."src/Trait/DotenvTrait.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 10
end_line = 10

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 11
end_line = 102

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 13
end_line = 330

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 29
end_line = 93

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 29
end_line = 93

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "kan-defect"
start_line = 13
end_line = 330

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "too-many-methods"
start_line = 13
end_line = 330

[[entries."tests/src/Abstract/Helper/LoadEnvDisabledKernel.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 14
end_line = 14

[[entries."tests/src/Abstract/Helper/WebKernel.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 25
end_line = 25

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "no-global"
start_line = 115
end_line = 115

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 62
end_line = 62

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 90
end_line = 90

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "return-type"
start_line = 152
end_line = 154
