[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "ambiguous-instantiation-target"
start_line = 97
end_line = 97

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "docblock-type-mismatch"
start_line = 111
end_line = 111

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-class-string-expression"
start_line = 97
end_line = 97

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-class-string-expression"
start_line = 97
end_line = 97

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 79
end_line = 79

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 79
end_line = 79

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 131
end_line = 131

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 131
end_line = 131

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-argument"
start_line = 100
end_line = 100

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-argument"
start_line = 105
end_line = 105

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-argument"
start_line = 106
end_line = 106

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 99
end_line = 99

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 99
end_line = 99

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-property-type-coercion"
start_line = 49
end_line = 49

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "named-argument-not-allowed"
start_line = 100
end_line = 100

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-value"
start_line = 79
end_line = 79

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "non-existent-property"
start_line = 49
end_line = 49

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "non-existent-property"
start_line = 49
end_line = 49

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possibly-invalid-argument"
start_line = 116
end_line = 116

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possibly-invalid-iterator"
start_line = 99
end_line = 99

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "property-type-coercion"
start_line = 50
end_line = 50

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "redundant-comparison"
start_line = 131
end_line = 131

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "redundant-condition"
start_line = 131
end_line = 131

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "unknown-class-instantiation"
start_line = 97
end_line = 97

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "unknown-class-instantiation"
start_line = 102
end_line = 102

[[entries."src/Abstract/AbstractSecurity.php".issues]]
code = "named-argument-not-allowed"
start_line = 28
end_line = 28

[[entries."src/Attribute/Configuration.php".issues]]
code = "mixed-operand"
start_line = 33
end_line = 33

[[entries."src/Attribute/Configuration.php".issues]]
code = "mixed-operand"
start_line = 35
end_line = 35

[[entries."src/Core/Security.php".issues]]
code = "invalid-property-read"
start_line = 17
end_line = 17

[[entries."src/Core/System.php".issues]]
code = "impossible-assignment"
start_line = 38
end_line = 38

[[entries."src/Core/System.php".issues]]
code = "invalid-property-read"
start_line = 38
end_line = 38

[[entries."src/Core/System.php".issues]]
code = "invalid-property-read"
start_line = 47
end_line = 47

[[entries."src/Core/System.php".issues]]
code = "no-value"
start_line = 47
end_line = 47

[[entries."src/Exception/WaffleException.php".issues]]
code = "invalid-return-statement"
start_line = 23
end_line = 27

[[entries."src/Router/Router.php".issues]]
code = "invalid-property-assignment-value"
start_line = 153
end_line = 153

[[entries."src/Router/Router.php".issues]]
code = "invalid-property-read"
start_line = 241
end_line = 241

[[entries."src/Router/Router.php".issues]]
code = "named-argument-not-allowed"
start_line = 99
end_line = 99

[[entries."src/Router/Router.php".issues]]
code = "named-argument-not-allowed"
start_line = 100
end_line = 100

[[entries."src/Router/Router.php".issues]]
code = "named-argument-not-allowed"
start_line = 237
end_line = 237

[[entries."src/Router/Router.php".issues]]
code = "non-existent-method"
start_line = 137
end_line = 137

[[entries."src/Router/Router.php".issues]]
code = "non-existent-method"
start_line = 137
end_line = 137

[[entries."src/Router/Router.php".issues]]
code = "possible-method-access-on-null"
start_line = 137
end_line = 137

[[entries."src/Router/Router.php".issues]]
code = "possibly-invalid-argument"
start_line = 129
end_line = 129

[[entries."src/Router/Router.php".issues]]
code = "reference-to-undefined-variable"
start_line = 225
end_line = 225

[[entries."src/Router/Router.php".issues]]
code = "unknown-class-instantiation"
start_line = 115
end_line = 115

[[entries."src/Router/Router.php".issues]]
code = "unknown-class-instantiation"
start_line = 239
end_line = 239

[[entries."src/Trait/DotenvTrait.php".issues]]
code = "mixed-operand"
start_line = 15
end_line = 15

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "invalid-generator-return-type"
start_line = 87
end_line = 87

[[entries."src/Trait/RenderingTrait.php".issues]]
code = "possibly-invalid-argument"
start_line = 24
end_line = 24

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 103
end_line = 103

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 123
end_line = 123

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 145
end_line = 145

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 150
end_line = 150

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 151
end_line = 151

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 185
end_line = 185

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 190
end_line = 190

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 191
end_line = 191

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 215
end_line = 215

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 237
end_line = 237

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 259
end_line = 259

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 300
end_line = 300

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 301
end_line = 301

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 325
end_line = 325

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 326
end_line = 326

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 162
end_line = 162

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 162
end_line = 162

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 274
end_line = 274

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 274
end_line = 274

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 30
end_line = 30

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 30
end_line = 30

[[entries."tests/src/Abstract/Helper/ConcreteTestKernel.php".issues]]
code = "mixed-operand"
start_line = 34
end_line = 34

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "mixed-return-statement"
start_line = 23
end_line = 23

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "mixed-return-statement"
start_line = 28
end_line = 28

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "non-existent-property"
start_line = 23
end_line = 23

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "non-existent-property"
start_line = 28
end_line = 28

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 22
end_line = 22

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 23
end_line = 23

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 39
end_line = 39

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 40
end_line = 40

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "string-member-selector"
start_line = 124
end_line = 124

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 39
end_line = 39

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 131
end_line = 131

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 136
end_line = 136

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 195
end_line = 195

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 204
end_line = 204

[[entries."tests/src/Core/SecurityTest.php".issues]]
code = "mixed-assignment"
start_line = 28
end_line = 28

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "invalid-property-read"
start_line = 43
end_line = 43

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "invalid-property-read"
start_line = 85
end_line = 85

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "no-value"
start_line = 43
end_line = 43

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "no-value"
start_line = 85
end_line = 85

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 78
end_line = 78

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 104
end_line = 104

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 126
end_line = 126

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 158
end_line = 158

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 205
end_line = 205

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "mixed-argument"
start_line = 184
end_line = 184

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "mixed-assignment"
start_line = 182
end_line = 182

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 78
end_line = 78

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 79
end_line = 79

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 112
end_line = 112

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 134
end_line = 134

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 205
end_line = 205

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 24
end_line = 24

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 25
end_line = 25

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 61
end_line = 61

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 61
end_line = 61

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 63
end_line = 63

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 63
end_line = 63

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 83
end_line = 83

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 83
end_line = 83

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 85
end_line = 85

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 85
end_line = 85

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 46
end_line = 46

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 69
end_line = 69

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 91
end_line = 91

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-assignment"
start_line = 30
end_line = 30

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-method-access"
start_line = 63
end_line = 63

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-operand"
start_line = 34
end_line = 34

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-operand"
start_line = 38
end_line = 38

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "ambiguous-object-method-access"
start_line = 38
end_line = 38

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "ambiguous-object-method-access"
start_line = 59
end_line = 59

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "ambiguous-object-method-access"
start_line = 76
end_line = 76

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "possibly-invalid-argument"
start_line = 121
end_line = 121

[[entries."tests/src/Trait/SystemTraitTest.php".issues]]
code = "possibly-false-argument"
start_line = 23
end_line = 23
