[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "possibly-null-argument"
start_line = 91
end_line = 91

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "possibly-null-argument"
start_line = 126
end_line = 126

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "docblock-type-mismatch"
start_line = 121
end_line = 121

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "less-specific-nested-argument-type"
start_line = 127
end_line = 127

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 104
end_line = 104

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 110
end_line = 110

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possible-method-access-on-null"
start_line = 100
end_line = 100

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possible-method-access-on-null"
start_line = 104
end_line = 104

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possible-method-access-on-null"
start_line = 109
end_line = 109

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possible-method-access-on-null"
start_line = 110
end_line = 110

[[entries."src/Core/Container.php".issues]]
code = "invalid-callable"
start_line = 47
end_line = 47

[[entries."src/Core/Container.php".issues]]
code = "invalid-property-assignment-value"
start_line = 85
end_line = 85

[[entries."src/Core/Container.php".issues]]
code = "invalid-return-statement"
start_line = 116
end_line = 116

[[entries."src/Core/Container.php".issues]]
code = "less-specific-nested-return-statement"
start_line = 143
end_line = 143

[[entries."src/Core/Container.php".issues]]
code = "mixed-argument"
start_line = 140
end_line = 140

[[entries."src/Core/Container.php".issues]]
code = "mixed-assignment"
start_line = 47
end_line = 47

[[entries."src/Core/Container.php".issues]]
code = "mixed-property-type-coercion"
start_line = 61
end_line = 61

[[entries."src/Core/Container.php".issues]]
code = "mixed-return-statement"
start_line = 63
end_line = 63

[[entries."src/Core/Container.php".issues]]
code = "nullable-return-statement"
start_line = 116
end_line = 116

[[entries."src/Core/Container.php".issues]]
code = "too-many-arguments"
start_line = 101
end_line = 101

[[entries."src/Core/Container.php".issues]]
code = "unevaluated-code"
start_line = 66
end_line = 66

[[entries."src/Core/Container.php".issues]]
code = "unknown-class-instantiation"
start_line = 111
end_line = 111

[[entries."src/Core/System.php".issues]]
code = "possibly-null-argument"
start_line = 46
end_line = 46

[[entries."src/Router/Router.php".issues]]
code = "mixed-argument"
start_line = 121
end_line = 121

[[entries."src/Router/Router.php".issues]]
code = "mixed-argument"
start_line = 125
end_line = 125

[[entries."src/Router/Router.php".issues]]
code = "mixed-argument"
start_line = 248
end_line = 248

[[entries."src/Router/Router.php".issues]]
code = "mixed-assignment"
start_line = 119
end_line = 119

[[entries."src/Router/Router.php".issues]]
code = "mixed-assignment"
start_line = 246
end_line = 246

[[entries."src/Router/Router.php".issues]]
code = "possible-method-access-on-null"
start_line = 118
end_line = 118

[[entries."src/Router/Router.php".issues]]
code = "possible-method-access-on-null"
start_line = 119
end_line = 119

[[entries."src/Router/Router.php".issues]]
code = "possible-method-access-on-null"
start_line = 245
end_line = 245

[[entries."src/Router/Router.php".issues]]
code = "possible-method-access-on-null"
start_line = 246
end_line = 246

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "string-member-selector"
start_line = 124
end_line = 124

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "possibly-invalid-argument"
start_line = 119
end_line = 119
