[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "ambiguous-instantiation-target"
start_line = 98
end_line = 98

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "docblock-type-mismatch"
start_line = 110
end_line = 110

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "impossible-assignment"
start_line = 131
end_line = 131

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-class-string-expression"
start_line = 98
end_line = 98

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-class-string-expression"
start_line = 98
end_line = 98

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 80
end_line = 80

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 80
end_line = 80

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 130
end_line = 130

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "invalid-property-read"
start_line = 130
end_line = 130

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-argument"
start_line = 102
end_line = 102

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-argument"
start_line = 104
end_line = 104

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-argument"
start_line = 105
end_line = 105

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 100
end_line = 100

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 100
end_line = 100

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-property-type-coercion"
start_line = 44
end_line = 44

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "named-argument-not-allowed"
start_line = 102
end_line = 102

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-value"
start_line = 80
end_line = 80

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-value"
start_line = 132
end_line = 132

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "non-existent-property"
start_line = 44
end_line = 44

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "non-existent-property"
start_line = 44
end_line = 44

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possibly-invalid-argument"
start_line = 115
end_line = 115

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possibly-invalid-iterator"
start_line = 100
end_line = 100

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "property-type-coercion"
start_line = 45
end_line = 45

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "redundant-comparison"
start_line = 130
end_line = 130

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "redundant-condition"
start_line = 130
end_line = 130

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "redundant-null-coalesce"
start_line = 131
end_line = 131

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "redundant-null-coalesce"
start_line = 132
end_line = 132

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "unknown-class-instantiation"
start_line = 98
end_line = 98

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "unknown-class-instantiation"
start_line = 101
end_line = 101

[[entries."src/Abstract/AbstractSecurity.php".issues]]
code = "named-argument-not-allowed"
start_line = 28
end_line = 28

[[entries."src/Attribute/Configuration.php".issues]]
code = "mixed-operand"
start_line = 28
end_line = 28

[[entries."src/Attribute/Configuration.php".issues]]
code = "mixed-operand"
start_line = 29
end_line = 29

[[entries."src/Core/Security.php".issues]]
code = "invalid-property-read"
start_line = 14
end_line = 14

[[entries."src/Core/System.php".issues]]
code = "impossible-assignment"
start_line = 35
end_line = 35

[[entries."src/Core/System.php".issues]]
code = "invalid-property-read"
start_line = 35
end_line = 35

[[entries."src/Core/System.php".issues]]
code = "invalid-property-read"
start_line = 44
end_line = 44

[[entries."src/Core/System.php".issues]]
code = "no-value"
start_line = 44
end_line = 44

[[entries."src/Exception/WaffleException.php".issues]]
code = "invalid-return-statement"
start_line = 23
end_line = 27

[[entries."src/Router/Router.php".issues]]
code = "invalid-property-assignment-value"
start_line = 152
end_line = 152

[[entries."src/Router/Router.php".issues]]
code = "invalid-property-read"
start_line = 239
end_line = 239

[[entries."src/Router/Router.php".issues]]
code = "named-argument-not-allowed"
start_line = 98
end_line = 98

[[entries."src/Router/Router.php".issues]]
code = "named-argument-not-allowed"
start_line = 99
end_line = 99

[[entries."src/Router/Router.php".issues]]
code = "named-argument-not-allowed"
start_line = 236
end_line = 236

[[entries."src/Router/Router.php".issues]]
code = "non-existent-method"
start_line = 136
end_line = 136

[[entries."src/Router/Router.php".issues]]
code = "non-existent-method"
start_line = 136
end_line = 136

[[entries."src/Router/Router.php".issues]]
code = "possible-method-access-on-null"
start_line = 136
end_line = 136

[[entries."src/Router/Router.php".issues]]
code = "possibly-invalid-argument"
start_line = 128
end_line = 128

[[entries."src/Router/Router.php".issues]]
code = "redundant-null-coalesce"
start_line = 205
end_line = 205

[[entries."src/Router/Router.php".issues]]
code = "reference-to-undefined-variable"
start_line = 225
end_line = 225

[[entries."src/Router/Router.php".issues]]
code = "unknown-class-instantiation"
start_line = 114
end_line = 114

[[entries."src/Router/Router.php".issues]]
code = "unknown-class-instantiation"
start_line = 237
end_line = 237

[[entries."src/Trait/DotenvTrait.php".issues]]
code = "mixed-operand"
start_line = 14
end_line = 14

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "invalid-generator-return-type"
start_line = 90
end_line = 90

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "redundant-isset-check"
start_line = 50
end_line = 50

[[entries."src/Trait/RenderingTrait.php".issues]]
code = "possibly-invalid-argument"
start_line = 24
end_line = 24

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 103
end_line = 103

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 123
end_line = 123

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 145
end_line = 145

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 150
end_line = 150

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 151
end_line = 151

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 181
end_line = 181

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 186
end_line = 186

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 187
end_line = 187

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 211
end_line = 211

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 233
end_line = 233

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 255
end_line = 255

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 292
end_line = 292

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 293
end_line = 293

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 317
end_line = 317

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "named-argument-not-allowed"
start_line = 318
end_line = 318

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 158
end_line = 158

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 158
end_line = 158

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 266
end_line = 266

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "non-existent-method"
start_line = 266
end_line = 266

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 30
end_line = 30

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 30
end_line = 30

[[entries."tests/src/Abstract/Helper/ConcreteTestKernel.php".issues]]
code = "mixed-operand"
start_line = 34
end_line = 34

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "mixed-return-statement"
start_line = 23
end_line = 23

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "mixed-return-statement"
start_line = 28
end_line = 28

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "non-existent-property"
start_line = 23
end_line = 23

[[entries."tests/src/Abstract/Helper/ConcreteTestResponse.php".issues]]
code = "non-existent-property"
start_line = 28
end_line = 28

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 19
end_line = 19

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 20
end_line = 20

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 36
end_line = 36

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "mixed-operand"
start_line = 38
end_line = 38

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "string-member-selector"
start_line = 122
end_line = 122

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 129
end_line = 129

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 134
end_line = 134

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 193
end_line = 193

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "redundant-cast"
start_line = 202
end_line = 202

[[entries."tests/src/Core/SecurityTest.php".issues]]
code = "mixed-assignment"
start_line = 28
end_line = 28

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "invalid-property-read"
start_line = 43
end_line = 43

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "invalid-property-read"
start_line = 85
end_line = 85

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "no-value"
start_line = 43
end_line = 43

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "no-value"
start_line = 85
end_line = 85

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 77
end_line = 77

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 103
end_line = 103

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 122
end_line = 122

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 154
end_line = 154

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "invalid-property-read"
start_line = 201
end_line = 201

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "mixed-argument"
start_line = 180
end_line = 180

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "mixed-assignment"
start_line = 178
end_line = 178

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 77
end_line = 77

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 78
end_line = 78

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 111
end_line = 111

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 130
end_line = 130

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-value"
start_line = 201
end_line = 201

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 21
end_line = 21

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 22
end_line = 22

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 58
end_line = 58

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 58
end_line = 58

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 60
end_line = 60

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 60
end_line = 60

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 80
end_line = 80

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 80
end_line = 80

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 82
end_line = 82

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "mixed-operand"
start_line = 82
end_line = 82

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 43
end_line = 43

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 66
end_line = 66

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 88
end_line = 88

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-assignment"
start_line = 27
end_line = 27

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-operand"
start_line = 31
end_line = 31

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "mixed-operand"
start_line = 35
end_line = 35

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "ambiguous-object-method-access"
start_line = 37
end_line = 37

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "ambiguous-object-method-access"
start_line = 57
end_line = 57

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "ambiguous-object-method-access"
start_line = 73
end_line = 73

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "possibly-invalid-argument"
start_line = 119
end_line = 119

[[entries."tests/src/Trait/SystemTraitTest.php".issues]]
code = "possibly-false-argument"
start_line = 23
end_line = 23
