[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 97
end_line = 97

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-global"
start_line = 19
end_line = 19

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-request-variable"
start_line = 68
end_line = 68

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "too-many-properties"
start_line = 13
end_line = 125

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 80
end_line = 80

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "tagged-todo"
start_line = 100
end_line = 100

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 101
end_line = 101

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-global"
start_line = 23
end_line = 23

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-request-variable"
start_line = 72
end_line = 72

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "too-many-properties"
start_line = 15
end_line = 142

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "cyclomatic-complexity"
start_line = 23
end_line = 166

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "kan-defect"
start_line = 23
end_line = 166

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 96
end_line = 96

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 96
end_line = 96

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-else-clause"
start_line = 102
end_line = 107

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-empty"
start_line = 143
end_line = 143

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-empty"
start_line = 143
end_line = 143

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 77
end_line = 77

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 77
end_line = 77

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 77
end_line = 77

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 77
end_line = 77

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 77
end_line = 77

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 78
end_line = 78

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-shorthand-ternary"
start_line = 131
end_line = 131

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-shorthand-ternary"
start_line = 132
end_line = 132

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "tagged-todo"
start_line = 144
end_line = 144

[[entries."src/Abstract/AbstractSecurity.php".issues]]
code = "braced-string-interpolation"
start_line = 40
end_line = 40

[[entries."src/Abstract/AbstractSecurity.php".issues]]
code = "braced-string-interpolation"
start_line = 51
end_line = 51

[[entries."src/Core/Cli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 10
end_line = 10

[[entries."src/Core/Request.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 10
end_line = 10

[[entries."src/Core/System.php".issues]]
code = "no-unsafe-finally"
start_line = 53
end_line = 53

[[entries."src/Interface/CliInterface.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 8
end_line = 8

[[entries."src/Interface/RequestInterface.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 8
end_line = 8

[[entries."src/Router/Router.php".issues]]
code = "cyclomatic-complexity"
start_line = 17
end_line = 296

[[entries."src/Router/Router.php".issues]]
code = "excessive-nesting"
start_line = 137
end_line = 142

[[entries."src/Router/Router.php".issues]]
code = "halstead"
start_line = 57
end_line = 72

[[entries."src/Router/Router.php".issues]]
code = "kan-defect"
start_line = 17
end_line = 296

[[entries."src/Router/Router.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 65
end_line = 65

[[entries."src/Router/Router.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 88
end_line = 88

[[entries."src/Router/Router.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 114
end_line = 114

[[entries."src/Router/Router.php".issues]]
code = "no-else-clause"
start_line = 97
end_line = 104

[[entries."src/Router/Router.php".issues]]
code = "no-empty"
start_line = 232
end_line = 232

[[entries."src/Router/Router.php".issues]]
code = "no-error-control-operator"
start_line = 166
end_line = 166

[[entries."src/Router/Router.php".issues]]
code = "no-multi-assignments"
start_line = 64
end_line = 64

[[entries."src/Router/Router.php".issues]]
code = "no-shorthand-ternary"
start_line = 134
end_line = 134

[[entries."src/Router/Router.php".issues]]
code = "no-shorthand-ternary"
start_line = 135
end_line = 135

[[entries."src/Router/Router.php".issues]]
code = "no-shorthand-ternary"
start_line = 208
end_line = 208

[[entries."src/Router/Router.php".issues]]
code = "parameter-type"
start_line = 189
end_line = 189

[[entries."src/Router/Router.php".issues]]
code = "return-type"
start_line = 189
end_line = 189

[[entries."src/Router/Router.php".issues]]
code = "tagged-todo"
start_line = 95
end_line = 95

[[entries."src/Trait/DotenvTrait.php".issues]]
code = "braced-string-interpolation"
start_line = 15
end_line = 15

[[entries."src/Trait/DotenvTrait.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 10
end_line = 10

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 10
end_line = 95

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "halstead"
start_line = 12
end_line = 53

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 15
end_line = 15

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "no-else-clause"
start_line = 31
end_line = 33

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "no-empty"
start_line = 48
end_line = 48

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "no-multi-assignments"
start_line = 57
end_line = 57

[[entries."src/Trait/RequestTrait.php".issues]]
code = "no-empty"
start_line = 16
end_line = 16

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 12
end_line = 349

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 28
end_line = 92

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 28
end_line = 92

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "kan-defect"
start_line = 12
end_line = 349

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "parameter-type"
start_line = 21
end_line = 21

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "return-type"
start_line = 21
end_line = 21

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "too-many-methods"
start_line = 12
end_line = 349

[[entries."src/Trait/SystemTrait.php".issues]]
code = "tagged-todo"
start_line = 8
end_line = 8

[[entries."tests/src/Abstract/AbstractSecurityTest.php".issues]]
code = "assertion-style"
start_line = 24
end_line = 24

[[entries."tests/src/Abstract/Helper/LoadEnvDisabledKernel.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 16
end_line = 16

[[entries."tests/src/Abstract/Helper/WebKernel.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 29
end_line = 29

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "explicit-octal"
start_line = 24
end_line = 24

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "explicit-octal"
start_line = 25
end_line = 25

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "no-error-control-operator"
start_line = 40
end_line = 40

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "no-global"
start_line = 117
end_line = 117

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "no-else-clause"
start_line = 40
end_line = 42

[[entries."tests/src/Exception/WaffleExceptionTest.php".issues]]
code = "assertion-style"
start_line = 30
end_line = 30

[[entries."tests/src/Exception/WaffleExceptionTest.php".issues]]
code = "assertion-style"
start_line = 31
end_line = 31

[[entries."tests/src/Exception/WaffleExceptionTest.php".issues]]
code = "assertion-style"
start_line = 32
end_line = 32

[[entries."tests/src/Exception/WaffleExceptionTest.php".issues]]
code = "assertion-style"
start_line = 33
end_line = 33

[[entries."tests/src/Exception/WaffleExceptionTest.php".issues]]
code = "assertion-style"
start_line = 36
end_line = 36

[[entries."tests/src/Exception/WaffleExceptionTest.php".issues]]
code = "assertion-style"
start_line = 37
end_line = 37

[[entries."tests/src/Exception/WaffleExceptionTest.php".issues]]
code = "assertion-style"
start_line = 38
end_line = 38

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 58
end_line = 58

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 80
end_line = 80

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "parameter-type"
start_line = 63
end_line = 63

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "return-type"
start_line = 63
end_line = 63

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "return-type"
start_line = 156
end_line = 158
