[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "possibly-null-argument"
start_line = 103
end_line = 103

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "possibly-null-argument"
start_line = 119
end_line = 119

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "possibly-null-argument"
start_line = 139
end_line = 139

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "docblock-type-mismatch"
start_line = 121
end_line = 121

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "less-specific-nested-argument-type"
start_line = 127
end_line = 127

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 104
end_line = 104

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "mixed-assignment"
start_line = 110
end_line = 110

[[entries."src/Core/Container.php".issues]]
code = "invalid-callable"
start_line = 56
end_line = 56

[[entries."src/Core/Container.php".issues]]
code = "invalid-property-assignment-value"
start_line = 80
end_line = 80

[[entries."src/Core/Container.php".issues]]
code = "invalid-return-statement"
start_line = 103
end_line = 103

[[entries."src/Core/Container.php".issues]]
code = "less-specific-nested-return-statement"
start_line = 130
end_line = 130

[[entries."src/Core/Container.php".issues]]
code = "mixed-argument"
start_line = 61
end_line = 61

[[entries."src/Core/Container.php".issues]]
code = "mixed-argument"
start_line = 127
end_line = 127

[[entries."src/Core/Container.php".issues]]
code = "mixed-assignment"
start_line = 55
end_line = 55

[[entries."src/Core/Container.php".issues]]
code = "mixed-property-type-coercion"
start_line = 63
end_line = 63

[[entries."src/Core/Container.php".issues]]
code = "mixed-return-statement"
start_line = 65
end_line = 65

[[entries."src/Core/Container.php".issues]]
code = "nullable-return-statement"
start_line = 103
end_line = 103

[[entries."src/Core/Container.php".issues]]
code = "too-many-arguments"
start_line = 88
end_line = 88

[[entries."src/Core/Container.php".issues]]
code = "unevaluated-code"
start_line = 67
end_line = 67

[[entries."src/Core/Container.php".issues]]
code = "unknown-class-instantiation"
start_line = 98
end_line = 98

[[entries."src/Router/Router.php".issues]]
code = "mixed-argument"
start_line = 118
end_line = 118

[[entries."src/Router/Router.php".issues]]
code = "mixed-argument"
start_line = 121
end_line = 121

[[entries."src/Router/Router.php".issues]]
code = "mixed-argument"
start_line = 209
end_line = 209

[[entries."src/Router/Router.php".issues]]
code = "mixed-assignment"
start_line = 117
end_line = 117

[[entries."src/Router/Router.php".issues]]
code = "mixed-assignment"
start_line = 208
end_line = 208

[[entries."src/Router/Router.php".issues]]
code = "non-existent-method"
start_line = 130
end_line = 130

[[entries."src/Router/Router.php".issues]]
code = "non-existent-method"
start_line = 130
end_line = 130

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "string-member-selector"
start_line = 137
end_line = 137

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "possibly-invalid-argument"
start_line = 118
end_line = 118
