[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 98
end_line = 98

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 101
end_line = 101

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-global"
start_line = 17
end_line = 17

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-request-variable"
start_line = 66
end_line = 66

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "too-many-properties"
start_line = 11
end_line = 130

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 102
end_line = 102

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 105
end_line = 105

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-global"
start_line = 21
end_line = 21

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-request-variable"
start_line = 70
end_line = 70

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "too-many-properties"
start_line = 13
end_line = 147

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "cyclomatic-complexity"
start_line = 17
end_line = 182

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "kan-defect"
start_line = 17
end_line = 182

[[entries."src/Core/Cli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 11
end_line = 11

[[entries."src/Core/Container.php".issues]]
code = "halstead"
start_line = 40
end_line = 69

[[entries."src/Core/Request.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 11
end_line = 11

[[entries."src/Interface/CliInterface.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 41
end_line = 41

[[entries."src/Interface/RequestInterface.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 41
end_line = 41

[[entries."src/Router/Router.php".issues]]
code = "cyclomatic-complexity"
start_line = 16
end_line = 274

[[entries."src/Router/Router.php".issues]]
code = "excessive-nesting"
start_line = 128
end_line = 132

[[entries."src/Router/Router.php".issues]]
code = "halstead"
start_line = 57
end_line = 73

[[entries."src/Router/Router.php".issues]]
code = "kan-defect"
start_line = 16
end_line = 274

[[entries."src/Trait/DotenvTrait.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 10
end_line = 10

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 11
end_line = 102

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 13
end_line = 337

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 29
end_line = 93

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 29
end_line = 93

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "kan-defect"
start_line = 13
end_line = 337

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "too-many-methods"
start_line = 13
end_line = 337

[[entries."tests/src/Abstract/Helper/LoadEnvDisabledKernel.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 14
end_line = 14

[[entries."tests/src/Abstract/Helper/WebKernel.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 25
end_line = 25

[[entries."tests/src/Core/ContainerTest.php".issues]]
code = "assertion-style"
start_line = 119
end_line = 119

[[entries."tests/src/Core/ContainerTest.php".issues]]
code = "too-many-methods"
start_line = 18
end_line = 124

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "no-global"
start_line = 124
end_line = 124

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 62
end_line = 62

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 90
end_line = 90

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "return-type"
start_line = 151
end_line = 153
