[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "ambiguous-instantiation-target"
start_line = 99
end_line = 99

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "docblock-type-mismatch"
start_line = 116
end_line = 116

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "possibly-invalid-argument"
start_line = 122
end_line = 122

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "unknown-class-instantiation"
start_line = 99
end_line = 99

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "unknown-class-instantiation"
start_line = 105
end_line = 105

[[entries."src/Router/Router.php".issues]]
code = "ambiguous-instantiation-target"
start_line = 238
end_line = 238

[[entries."src/Router/Router.php".issues]]
code = "unknown-class-instantiation"
start_line = 112
end_line = 112

[[entries."src/Router/Router.php".issues]]
code = "unknown-class-instantiation"
start_line = 238
end_line = 238

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "string-member-selector"
start_line = 122
end_line = 122

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "possibly-invalid-argument"
start_line = 119
end_line = 119
