[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "cyclomatic-complexity"
start_line = 28
end_line = 247

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "too-many-properties"
start_line = 14
end_line = 141

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "cyclomatic-complexity"
start_line = 18
end_line = 185

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "kan-defect"
start_line = 18
end_line = 185

[[entries."src/Core/Config.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 74
end_line = 74

[[entries."src/Core/Config.php".issues]]
code = "no-else-clause"
start_line = 72
end_line = 75

[[entries."src/Core/Container.php".issues]]
code = "halstead"
start_line = 40
end_line = 69

[[entries."src/Core/YamlParser.php".issues]]
code = "cyclomatic-complexity"
start_line = 13
end_line = 132

[[entries."src/Core/YamlParser.php".issues]]
code = "halstead"
start_line = 40
end_line = 98

[[entries."src/Core/YamlParser.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 29
end_line = 29

[[entries."src/Core/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 65
end_line = 70

[[entries."src/Core/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 71
end_line = 76

[[entries."src/Core/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 84
end_line = 95

[[entries."src/Core/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 92
end_line = 94

[[entries."src/Core/YamlParser.php".issues]]
code = "no-empty"
start_line = 90
end_line = 90

[[entries."src/Router/Router.php".issues]]
code = "cyclomatic-complexity"
start_line = 16
end_line = 274

[[entries."src/Router/Router.php".issues]]
code = "excessive-nesting"
start_line = 128
end_line = 132

[[entries."src/Router/Router.php".issues]]
code = "halstead"
start_line = 57
end_line = 73

[[entries."src/Router/Router.php".issues]]
code = "kan-defect"
start_line = 16
end_line = 274

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 11
end_line = 102

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 13
end_line = 337

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 29
end_line = 91

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "kan-defect"
start_line = 13
end_line = 337

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "too-many-methods"
start_line = 13
end_line = 337

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 47
end_line = 47

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 64
end_line = 64

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 91
end_line = 91

[[entries."tests/src/Abstract/AbstractResponseTest.php".issues]]
code = "cyclomatic-complexity"
start_line = 15
end_line = 122

[[entries."tests/src/Core/ContainerTest.php".issues]]
code = "too-many-methods"
start_line = 19
end_line = 140

[[entries."tests/src/Core/Helper/Uninstantiable.php".issues]]
code = "class-name"
start_line = 6
end_line = 6

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "no-global"
start_line = 116
end_line = 116

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "cyclomatic-complexity"
start_line = 15
end_line = 258

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "no-request-variable"
start_line = 112
end_line = 112

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 65
end_line = 65

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 87
end_line = 87

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 129
end_line = 129

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 200
end_line = 200

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 253
end_line = 253

[[entries."tests/src/Core/SystemTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 77
end_line = 77

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "cyclomatic-complexity"
start_line = 21
end_line = 257

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-request-variable"
start_line = 116
end_line = 116

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-request-variable"
start_line = 149
end_line = 149

[[entries."tests/src/Router/RouterTest.php".issues]]
code = "no-request-variable"
start_line = 195
end_line = 195

[[entries."tests/src/TestCase.php".issues]]
code = "class-name"
start_line = 18
end_line = 18

[[entries."tests/src/TestCase.php".issues]]
code = "too-many-methods"
start_line = 18
end_line = 163

[[entries."tests/src/Trait/Helper/Service.php".issues]]
code = "class-name"
start_line = 6
end_line = 6

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 37
end_line = 37

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 54
end_line = 54

[[entries."tests/src/Trait/RenderingTraitTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 70
end_line = 70

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "return-type"
start_line = 165
end_line = 167
