[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 97
end_line = 97

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-global"
start_line = 19
end_line = 19

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-request-variable"
start_line = 68
end_line = 68

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "too-many-properties"
start_line = 13
end_line = 125

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 80
end_line = 80

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "tagged-todo"
start_line = 100
end_line = 100

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 101
end_line = 101

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-global"
start_line = 23
end_line = 23

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-request-variable"
start_line = 72
end_line = 72

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "too-many-properties"
start_line = 15
end_line = 142

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "cyclomatic-complexity"
start_line = 23
end_line = 169

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "kan-defect"
start_line = 23
end_line = 169

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 96
end_line = 96

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 96
end_line = 96

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-else-clause"
start_line = 103
end_line = 108

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 77
end_line = 77

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 77
end_line = 77

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 77
end_line = 77

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 77
end_line = 77

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 77
end_line = 77

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-multi-assignments"
start_line = 78
end_line = 78

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-shorthand-ternary"
start_line = 132
end_line = 132

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "no-shorthand-ternary"
start_line = 133
end_line = 133

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "tagged-todo"
start_line = 147
end_line = 147

[[entries."src/Abstract/AbstractSecurity.php".issues]]
code = "braced-string-interpolation"
start_line = 38
end_line = 38

[[entries."src/Abstract/AbstractSecurity.php".issues]]
code = "braced-string-interpolation"
start_line = 47
end_line = 47

[[entries."src/Core/Cli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 13
end_line = 13

[[entries."src/Core/Request.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 13
end_line = 13

[[entries."src/Core/System.php".issues]]
code = "no-unsafe-finally"
start_line = 56
end_line = 56

[[entries."src/Interface/CliInterface.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 8
end_line = 8

[[entries."src/Interface/RequestInterface.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 8
end_line = 8

[[entries."src/Router/Router.php".issues]]
code = "cyclomatic-complexity"
start_line = 17
end_line = 309

[[entries."src/Router/Router.php".issues]]
code = "excessive-nesting"
start_line = 134
end_line = 139

[[entries."src/Router/Router.php".issues]]
code = "halstead"
start_line = 58
end_line = 73

[[entries."src/Router/Router.php".issues]]
code = "kan-defect"
start_line = 17
end_line = 309

[[entries."src/Router/Router.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 66
end_line = 66

[[entries."src/Router/Router.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 89
end_line = 89

[[entries."src/Router/Router.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 113
end_line = 113

[[entries."src/Router/Router.php".issues]]
code = "no-else-clause"
start_line = 98
end_line = 103

[[entries."src/Router/Router.php".issues]]
code = "no-empty"
start_line = 230
end_line = 230

[[entries."src/Router/Router.php".issues]]
code = "no-error-control-operator"
start_line = 163
end_line = 163

[[entries."src/Router/Router.php".issues]]
code = "no-multi-assignments"
start_line = 65
end_line = 65

[[entries."src/Router/Router.php".issues]]
code = "no-shorthand-ternary"
start_line = 205
end_line = 205

[[entries."src/Router/Router.php".issues]]
code = "parameter-type"
start_line = 186
end_line = 186

[[entries."src/Router/Router.php".issues]]
code = "return-type"
start_line = 186
end_line = 186

[[entries."src/Router/Router.php".issues]]
code = "tagged-todo"
start_line = 96
end_line = 96

[[entries."src/Trait/DotenvTrait.php".issues]]
code = "braced-string-interpolation"
start_line = 15
end_line = 15

[[entries."src/Trait/DotenvTrait.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 10
end_line = 10

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 10
end_line = 100

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "halstead"
start_line = 12
end_line = 53

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 15
end_line = 15

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "no-else-clause"
start_line = 31
end_line = 33

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "no-empty"
start_line = 48
end_line = 48

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "no-multi-assignments"
start_line = 62
end_line = 62

[[entries."src/Trait/RequestTrait.php".issues]]
code = "no-empty"
start_line = 16
end_line = 16

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 12
end_line = 353

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 28
end_line = 92

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 28
end_line = 92

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "kan-defect"
start_line = 12
end_line = 353

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "parameter-type"
start_line = 21
end_line = 21

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "return-type"
start_line = 21
end_line = 21

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "too-many-methods"
start_line = 12
end_line = 353

[[entries."src/Trait/SystemTrait.php".issues]]
code = "tagged-todo"
start_line = 8
end_line = 8

[[entries."tests/src/Abstract/Helper/LoadEnvDisabledKernel.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 17
end_line = 17

[[entries."tests/src/Abstract/Helper/WebKernel.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 31
end_line = 31

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "explicit-octal"
start_line = 24
end_line = 24

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "explicit-octal"
start_line = 25
end_line = 25

[[entries."tests/src/Attribute/ConfigurationTest.php".issues]]
code = "no-error-control-operator"
start_line = 40
end_line = 40

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "no-global"
start_line = 117
end_line = 117

[[entries."tests/src/Core/ResponseTest.php".issues]]
code = "no-else-clause"
start_line = 40
end_line = 42

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 58
end_line = 58

[[entries."tests/src/Trait/DotenvTraitTest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 80
end_line = 80

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "parameter-type"
start_line = 63
end_line = 63

[[entries."tests/src/Trait/ReflectionTraitTest.php".issues]]
code = "return-type"
start_line = 63
end_line = 63

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "return-type"
start_line = 156
end_line = 158
