[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 98
end_line = 98

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 101
end_line = 101

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-global"
start_line = 17
end_line = 17

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "no-request-variable"
start_line = 66
end_line = 66

[[entries."src/Abstract/AbstractCli.php".issues]]
code = "too-many-properties"
start_line = 11
end_line = 130

[[entries."src/Abstract/AbstractKernel.php".issues]]
code = "cyclomatic-complexity"
start_line = 26
end_line = 220

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 102
end_line = 102

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 105
end_line = 105

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-global"
start_line = 21
end_line = 21

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "no-request-variable"
start_line = 70
end_line = 70

[[entries."src/Abstract/AbstractRequest.php".issues]]
code = "too-many-properties"
start_line = 13
end_line = 147

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "cyclomatic-complexity"
start_line = 17
end_line = 184

[[entries."src/Abstract/AbstractResponse.php".issues]]
code = "kan-defect"
start_line = 17
end_line = 184

[[entries."src/Core/Cli.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 11
end_line = 11

[[entries."src/Core/Config.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 10
end_line = 10

[[entries."src/Core/Config.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 72
end_line = 72

[[entries."src/Core/Config.php".issues]]
code = "no-else-clause"
start_line = 70
end_line = 73

[[entries."src/Core/Container.php".issues]]
code = "halstead"
start_line = 40
end_line = 69

[[entries."src/Core/Request.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 11
end_line = 11

[[entries."src/Core/YamlParser.php".issues]]
code = "cyclomatic-complexity"
start_line = 11
end_line = 129

[[entries."src/Core/YamlParser.php".issues]]
code = "halstead"
start_line = 37
end_line = 95

[[entries."src/Core/YamlParser.php".issues]]
code = "no-boolean-literal-comparison"
start_line = 26
end_line = 26

[[entries."src/Core/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 62
end_line = 67

[[entries."src/Core/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 68
end_line = 73

[[entries."src/Core/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 81
end_line = 92

[[entries."src/Core/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 89
end_line = 91

[[entries."src/Core/YamlParser.php".issues]]
code = "no-empty"
start_line = 87
end_line = 87

[[entries."src/Interface/CliInterface.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 41
end_line = 41

[[entries."src/Interface/RequestInterface.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 41
end_line = 41

[[entries."src/Router/Router.php".issues]]
code = "cyclomatic-complexity"
start_line = 16
end_line = 274

[[entries."src/Router/Router.php".issues]]
code = "excessive-nesting"
start_line = 128
end_line = 132

[[entries."src/Router/Router.php".issues]]
code = "halstead"
start_line = 57
end_line = 73

[[entries."src/Router/Router.php".issues]]
code = "kan-defect"
start_line = 16
end_line = 274

[[entries."src/Trait/ReflectionTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 11
end_line = 102

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "cyclomatic-complexity"
start_line = 13
end_line = 337

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 29
end_line = 93

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "halstead"
start_line = 29
end_line = 93

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "kan-defect"
start_line = 13
end_line = 337

[[entries."src/Trait/SecurityTrait.php".issues]]
code = "too-many-methods"
start_line = 13
end_line = 337

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 46
end_line = 46

[[entries."tests/src/Abstract/AbstractKernelTest.php".issues]]
code = "no-shorthand-ternary"
start_line = 62
end_line = 62

[[entries."tests/src/Core/ContainerTest.php".issues]]
code = "too-many-methods"
start_line = 18
end_line = 123

[[entries."tests/src/Core/RequestTest.php".issues]]
code = "no-global"
start_line = 115
end_line = 115

[[entries."tests/src/TestCase.php".issues]]
code = "class-name"
start_line = 16
end_line = 16

[[entries."tests/src/TestCase.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 108
end_line = 108

[[entries."tests/src/TestCase.php".issues]]
code = "too-many-methods"
start_line = 16
end_line = 123

[[entries."tests/src/Trait/SecurityTraitTest.php".issues]]
code = "return-type"
start_line = 151
end_line = 153
