# GitHub Actions for Symfony: PHP Analysis
name: PHP analysis, tests & build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  composer:
    name: Composer Analysis (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04]
        php-versions: ['8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, pgsql, pdo_mysql, pdo_pgsql, gmp, fileinfo, intl, opcache, xml, iconv, redis, mailparse
          coverage: xdebug
          tools: composer:v2

      - name: Restore cached files
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            vendor/
            var/cache/
          key: ${{ runner.os }}-PHP${{ matrix.php-versions }}-cache-${{ github.ref }}-${{ hashFiles('**/composer.lock') }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-PHP${{ matrix.php-versions }}-cache-${{ github.ref }}-${{ hashFiles('**/composer.lock') }}-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Linter (Mago Lint)
        if: success() || failure()
        run: vendor/bin/mago lint --reporting-format=github

      - name: Static Analysis Tool (Mago Analyze)
        if: success() || failure()
        run: vendor/bin/mago analyze --reporting-format=github

      - name: Security Audit of Composer Dependencies (SCA)
        if: success() || failure()
        run: composer audit

      - name: Security-focused Static Analysis (SAST)
        if: success() || failure()
        run: vendor/bin/psalm --taint-analysis

      - name: The PHP testing framework (PHPUnit)
        if: success() || failure()
        run: |
          vendor/bin/phpunit --log-junit var/data/phpunit-coverage/junit.xml --coverage-html var/data/phpunit-coverage
          vendor/bin/phpunit --coverage-clover ./var/data/phpunit-coverage/clover.xml

      - name: Upload coverage reports to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./var/data/phpunit-coverage/clover.xml

      - name: Save cache
        if: success() || failure()
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            vendor/
            var/cache/
          key: ${{ runner.os }}-PHP${{ matrix.php-versions }}-cache-${{ github.ref }}-${{ hashFiles('**/composer.lock') }}-${{ github.run_id }}
